import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <header style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '12px 16px',
          borderBottom: '1px solid #e5e7eb',
          position: 'sticky',
          top: 0,
          background: '#fff',
          zIndex: 40,
        }}>
          <Link href="/" style={{ fontWeight: 700, fontSize: 16, textDecoration: 'none', color: '#111827' }}>
            Calendapp
          </Link>
          <nav style={{ display: 'flex', gap: 12 }}>
            <Link href="/calendar" style={{ textDecoration: 'none', color: '#2563eb', fontWeight: 500 }}>
              Calendario
            </Link>
          </nav>
        </header>
        <main style={{ padding: 16 }}>
          {children}
        </main>
      </body>
    </html>
  );
}
